export const BOOKS = [
  {
    id: "A1234",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1235",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1236",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1237",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1238",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1239",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: true,
  },
  {
    id: "A1239",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: false,
    isRecomended: false,
  },
  {
    id: "A1239",
    judul: "IKIGAI",
    penulis: "HECTOR GARCIA",
    cover: "./src/IKIGAI.jpg",
    tahun: 2017,
    isCompleted: true,
    isRecomended: false,
  },
];
